name: Release binaries

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup
        run: |
          ./setup_libs.sh

      - name: Build
        run: |
          . ./env_vars.sh
          cd teddybox
          idf.py build
          /home/runner/.espressif/python_env/idf4.4_py3.9_env/bin/python ../esp-adf/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32s3  merge_bin -o merged-firmware.bin --flash_mode dio --flash_size 8MB --flash_freq 80m 0x0 build/bootloader/bootloader.bin 0x9000 build/partition_table/partition-table.bin 0x16f000 build/ota_data_initial.bin 0x180000 build/teddybox.bin
          mkdir espbinaries
          cp build/teddybox.bin espbinaries/teddybox_ota.bin
          cp merged-firmware.bin espbinaries/teddybox_full.bin
          
      - name: Add esp bins to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: teddybox/espbinaries/*
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
